apiVersion: v1
kind: Pod
metadata:
  name: rsapp
  namespace: default
  labels:
    app: rsapp
spec:
  containers:
  - name: app
    image: ichte/swarmtest:node
    resources:
      limits:
        cpu: 100m
        memory: 120Mi
    ports:
    - containerPort:  8085
    