apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rsbuoapp-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: rsapp
  minReplicas: 5
  maxReplicas: 10

  targetCPUUtilizationPercentage: 50
