apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rsapp
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: rsapp
  template:
    metadata:
      name: rsapp
      namespace: default
      labels:
        app: rsapp
    spec:
      containers:
      - name: app
        image: ichte/swarmtest:node
        resources:
          limits:
            cpu: 100m
            memory: 120Mi
        ports:
        - containerPort:  8085